# Generated by Django 4.1.7 on 2023-04-20 19:03

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_birth_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[app.validators.stop_domain]),
        ),
    ]
