# Generated by Django 4.1.7 on 2023-04-21 17:01

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[app.validators.check_birth_day]),
        ),
    ]
