# Generated by Django 4.1.7 on 2023-04-21 17:23

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, validators=[app.validators.stop_domain]),
        ),
    ]
